main-page:
  guest: guest
  "2023": newcomer
  default: at-school

main-presets:
  guest:
    - tag: grid
      header: 您可能想关注
      items:
        - text: 寝室
          icon: dorm
          path: guide/dorm/

        - text: 食堂
          icon: dining
          path: guide/dining/

        - text: 快递
          icon: express
          path: guide/express/

        - text: 洗浴
          icon: bath
          path: guide/bath/

        - text: 生活
          icon: life
          path: guide/life/

        - text: 转专业
          icon: change
          path: guide/change-major/

        - text: 师范生
          icon: teacher
          path: guide/normal/

        - text: 课程
          icon: content
          path: guide/course/

        - text: 学习
          icon: study
          path: guide/study/

        - text: 奖学金
          icon: metal
          path: intro/scholarship/

        - text: 考研/保研
          icon: study
          path: intro/grad/

  newcomer:
    - tag: grid
      header: 您可能想关注
      items:
        - text: 本科课程表
          icon: course-table
          url: under-course-table

        - text: 选课系统
          icon: select
          url: under-select

        - text: 专项考试成绩
          icon: test
          url: grade-special

        - text: 校园地图
          icon: map
          url: map

        - text: 学校通知
          icon: notice
          url: notice-list

      footer: 更多内容请详见下方其他 Tab 页

  at-school:
    - tag: grid
      header: 功能
      items:
        - text: 本科课程表
          icon: course-table
          url: under-course-table

        - text: 本科成绩查询
          icon: grade
          url: under-grade

        - text: 学校通知
          icon: notice
          url: notice-list

        - text: 学校新闻
          icon: news
          url: notice-list?type=news

        - text: 校园邮箱
          icon: email
          url: email-recent

        - text: 图书馆
          icon: library
          url: library

        - text: 校历
          icon: calendar
          url: calendar

        - text: 转专业计划
          icon: change
          url: change-major

      footer: 更多内容请详见下方其他 Tab 页

intro-page:
  guest:
    items:
      # - under-enroll
      # - grad-enroll
      # - about
      # - school
      - apartment
    more: []

  default:
    items:
      # - about
      # - school
      - apartment
    more:
      - under-enroll
      - grad-enroll

guide-page:
  guest:
    items:
      - life
      - study
      - enjoy
      # - newcomer
    more:
      # - account
      # - service
      # - tip
      - graduate

  "2023":
    items:
      - life
      - account
      - enjoy
      # - service
      - study
      # - tip
      # - newcomer
    more:
      - graduate

  "2020":
    items:
      - graduate
      - study
      # - service
      # - account
    more:
      - life
      - tip
      - enjoy
      - newcomer

  default:
    items:
      # - service
      - study
      - life
    more:
      # - account
      - tip
      - enjoy
      - newcomer
      - graduate

function-page:
  guest: guest
  default: at-school

function-presets:
  guest:
    - tag: grid
      header: 账号激活
      items:
        - text: 账号激活
          icon: authorize
          url: account-activate

    - tag: grid
      header: 东师风采
      items:
        - text: 校园地图
          icon: map
          url: map

        # - text: 音悦东师
        #   icon: cd
        #   url: music

        # - text: 影约东师
        #   icon: media
        #   url: video?type=video

        - text: 校园媒体
          icon: account
          url: school-media

    # - tag: grid
    #   header: 学校动态
    #   items:
    #     - text: 通知公告
    #       icon: notice
    #       url: official-notice-list

    #     - text: 要闻速递
    #       icon: news
    #       url: official-info-list?type=news

    #     - text: 媒体师大
    #       icon: media
    #       url: official-info-list?type=media

    #     - text: 人文社科
    #       icon: marx
    #       url: official-info-list?type=social

    #     - text: 自然科学
    #       icon: chemistry
    #       url: official-info-list?type=science

    #     - text: 学术预告
    #       icon: study
    #       url: official-academic-list

    - tag: grid
      header: 信息查询
      items:
        - text: 校历
          icon: calendar
          url: calendar

        - text: 东师网站
          icon: network
          url: website

        - text: 师大黄页
          icon: phone
          url: phone

    - tag: grid
      header: 工具
      items:
        - text: 体测计算器
          icon: calculate
          url: pe-calculator

        - text: 东师天气
          icon: sun
          url: weather

    - tag: grid
      header: 本科招生
      items:
        - text: 2024 年招生简章
          icon: rule
          path: intro/enroll/under/rule/

        - text: 2024 年招生计划
          icon: enroll
          url: under-enroll-plan

        - text: 历史分数线
          icon: time
          url: under-enroll-score

        # - text: 录取查询
        #   icon: letter
        #   url: admission?type=search

    - tag: list
      items:
        - text: 登录开启海量校园功能
          url: account-login
      footer: " "

  at-school:
    - tag: grid
      header: 融合门户
      items:
        - text: 学校通知
          icon: notice
          url: notice-list

        - text: 学校新闻
          icon: news
          url: notice-list?type=news

        - text: 图书馆
          icon: library
          url: library

    - tag: grid
      header: 本科教务系统
      items:
        - text: 本科课程表
          icon: course-table
          url: under-course-table

        - text: 本科成绩查询
          icon: grade
          url: under-grade

        - text: 选课系统
          icon: select
          url: under-select

        - text: 考场查询
          icon: test
          url: exam-place

        - text: 专项考试成绩
          icon: test
          url: grade-special

        - text: 学籍注册查看
          icon: archive
          url: under-archive-view

        # - text: 建立学籍
        #   icon: archive
        #   url: under-archive-create

        - text: 转专业计划
          icon: change
          url: change-major

        - text: 课程评价
          icon: heart
          url: under-commentary

    - tag: grid
      header: 东师风采
      items:
        - text: 校园地图
          icon: map
          url: map

        - text: 校园媒体
          icon: account
          url: school-media

    - tag: grid
      header: 信息查询
      items:
        - text: 校园邮箱邮件
          icon: email
          url: email-recent

        - text: 校历
          icon: calendar
          url: calendar

        - text: 东师网站
          icon: network
          url: website

        - text: 师大黄页
          icon: phone
          url: phone

    - tag: grid
      header: 账号相关
      items:
        - text: 账号激活
          icon: authorize
          url: account-activate

        - text: 邮箱申请
          icon: email
          url: email-apply

    - tag: grid
      header: 工具
      items:
        - text: 体测计算器
          icon: calculate
          url: pe-calculator

        - text: 东师天气
          icon: sun
          url: weather

      footer: " "

user:
  - tag: list
    items:
      - text: 使用指南
        icon: idea
        url: info?path=Oguide/

      - text: 更新日志
        icon: log
        url: info?path=Olog/

      - text: 隐私说明
        icon: privacy
        url: privacy

      - text: 关于
        icon: about
        url: about

  - tag: p
    heading: " "
    text:
      - 如果看过小程序后您还有疑问，欢迎加入 inNENU 咨询群 (1139044856) 进行咨询。
      - 小程序为 Mr.Hope 个人独自开发编写，现已花费 Mr.Hope 超 3300 小时，文字数量超过 108 万字。
    style: "color: #888; font-size: 14px"

  - tag: functional-list
    items:
      - text: 分享小程序
        icon: share
        type: button
        openType: share

      - text: 评价小程序
        icon: star
        url: action?action=rate

      - text: 联系 Mr.Hope
        icon: contact
        type: button
        openType: contact
        handler: reportInfo

about:
  - tag: list
    header: 小程序介绍
    items:
      - text: 小程序全部内容均由 Mr.Hope 独立开发。

      - text: 小程序现有字数为 1075989 字，其中东师指南部分 330563 字，新生迎新部分 105083 字，东师介绍部分 339346 字，机构介绍部分 70417 字，学院介绍部分 144879 字，功能大厅部分 38218 字，其他部分 47483 字。

      - text: Mr.Hope 个人介绍
        url: info?path=Oabout/mrhope

      - text: |-
          记: inNENU
        url: info?path=Oabout/history

      - text: 开发者访谈
        url: info?path=Oabout/interview

      - text: 常见问题
        url: info?path=Oabout/function

      - text: 致谢名单
        url: info?path=Oabout/thanks

  - tag: text
    heading: 小程序内容
    text:
      - 小程序页面内容仓库在 GitHub 上开源。如您愿意对小程序提供帮助，欢迎您点击下方链接为该仓库做贡献。您可以帮助扩充或编辑小程序的页面文字、图片以及相关文件。

  - tag: action
    content: https://github.com/inNENU/resource

  - tag: list
    header: 内容版权及使用
    items:
      - text: 请您特别注意，除标注来源的文字、图片 Mr.Hope 没有版权外，其余文字、图片均放置在『CC BY-NC-ND 4.0』协议下。请您合法使用这些文字与图片，以避免引起纠纷。

      - text: 协议详情
        url: info?path=Oabout/copyright

service:
  forceOnline: true

notice:
  main:
    title: 欢迎使用 inNENU
    content: 欢迎使用 inNENU。这是一个由 Mr.Hope 个人制作的非官方小程序，内含 108 万字的新生攻略。希望大家能够通过小程序摆脱对大学的迷茫。

update:
  force: false
  reset: false
