main-page:
  guest: guest
  "2024": newcomer
  default: at-school
  # default: wenenu

main-presets:
  wenenu:
    - tag: card
      cover: $img/tab/wenenu.png
      title: weNENU —— 我们的东师
      desc: 隆重推出 weNENU 小程序
      logo: $img/tab/wenenu-logo.png
      appId: wx2550e3fd373b79a8
      path: pages/main/main

  guest:
    # - tag: card
    #   cover: $img/tab/stream.png
    #   title: 经验分享与答疑
    #   path: newcomer/activity/streaming

    - tag: list
      items:
        - text: 登录开启海量校园功能
          url: account-login

    - tag: grid
      header: 报到相关
      items:
        - text: 到校路线
          icon: locate
          path: newcomer/arrival/

        - text: 新生报到
          icon: check
          path: newcomer/check/

        - text: 新生群
          icon: qq-group
          path: newcomer/contact/

        - text: 需带物品
          icon: necessity
          path: newcomer/necessity/

        - text: 军训
          icon: military
          path: newcomer/activity/military/

        - text: 入学活动
          icon: activity
          path: newcomer/activity/

        - text: 防盗防骗
          icon: safe
          path: newcomer/safety/

        - text: 校园地图
          icon: map
          url: map

    - tag: grid
      header: 您可能想关注
      items:
        - text: 寝室
          icon: dorm
          path: guide/dorm/

        - text: 食堂
          icon: dining
          path: guide/dining/

        - text: 快递
          icon: express
          path: guide/express/

        - text: 洗浴
          icon: bath
          path: guide/bath/

        - text: 生活
          icon: life
          path: guide/life/

        - text: 校园网
          icon: network
          path: guide/network/

        - text: 校园卡
          icon: card
          path: guide/card/

        - text: 课程
          icon: content
          path: guide/course/

        - text: 学习
          icon: study
          path: guide/study/

        - text: 奖学金
          icon: metal
          path: intro/scholarship/

        - text: 转专业
          icon: change
          path: guide/change-major/

        - text: 师范生
          icon: teacher
          path: guide/normal/

  newcomer:
    - tag: functional-list
      header: 如果你觉得 inNENU 对你有帮助，欢迎分享！
      items:
        - text: 向你的同学们分享小程序
          icon: share
          type: button
          openType: share

    - tag: grid
      header: 报到相关
      items:
        - text: 入学准备
          icon: prepare
          path: newcomer/prepare/

        - text: 到校路线
          icon: locate
          path: newcomer/arrival/

        - text: 新生报到
          icon: check
          path: newcomer/check/

        - text: 新生群
          icon: qq-group
          path: newcomer/contact/

        - text: 需带物品
          icon: necessity
          path: newcomer/necessity/

        - text: 入学活动
          icon: activity
          path: newcomer/activity/

        - text: 防盗防骗
          icon: safe
          path: newcomer/safety/

        - text: 校园地图
          icon: map
          url: map

    - tag: grid
      header: 校园介绍
      items:
        - text: 寝室
          icon: dorm
          path: guide/dorm/

        - text: 食堂
          icon: dining
          path: guide/dining/

        - text: 快递
          icon: express
          path: guide/express/

        - text: 洗浴
          icon: bath
          path: guide/bath/

        - text: 生活
          icon: life
          path: guide/life/

        - text: 课程
          icon: content
          path: guide/course/

        - text: 学习
          icon: study
          path: guide/study/

        - text: 奖学金
          icon: metal
          path: intro/scholarship/

        - text: 转专业
          icon: change
          path: guide/change-major/

        - text: 师范生
          icon: teacher
          path: guide/normal/

        - text: 专业介绍
          icon: study
          path: school/major

        - text: 学校通知
          icon: notice
          url: notice-list

        - text: 校园媒体
          icon: account
          url: school-media

        - text: 学生组织
          icon: student-org
          path: guide/org/

        - text: 社团
          icon: association
          path: guide/association/

      footer: 更多内容请详见下方其他 Tab 页

  at-school:
    - tag: grid
      header: 功能
      items:
        - text: 课程表
          icon: course-table
          url: course-table

        - text: 成绩查询
          icon: grade
          url: grade

        - text: 学校通知
          icon: notice
          url: notice-list

        - text: 学校新闻
          icon: news
          url: notice-list?type=news

        - text: 校园邮箱
          icon: email
          url: email-recent

        - text: 图书馆
          icon: library
          url: library

        - text: 校历
          icon: calendar
          url: calendar

        - text: 转专业计划
          icon: change
          url: change-major

      footer: 更多内容请详见下方其他 Tab 页

intro-page:
  guest:
    items:
      - under-enroll
      - grad-enroll
      - about
      - school
    more:
      - apartment

  default:
    items:
      - about
      - school
      - apartment
    more:
      - under-enroll
      - grad-enroll

  # default:
  #   items: []
  #   more: []

guide-page:
  guest:
    items:
      - newcomer
      - life
      - study
      - enjoy
      - normal
    more:
      - account
      - service
      - tip
      - graduate

  "2024":
    items:
      - newcomer
      - life
      - study
      - normal
      - enjoy
      - service
      - account
      - tip
    more:
      - graduate

  "2020":
    items:
      - graduate
      - study
      - service
      - account
    more:
      - life
      - tip
      - enjoy
      - newcomer

  default:
    items:
      - service
      - study
      - life
      - account
    more:
      - normal
      - tip
      - enjoy
      - newcomer
      - graduate

  # default:
  #   items: []
  #   more: []

function-page:
  guest: guest
  default: at-school
  # default: wenenu

function-presets:
  wenenu: []
  guest:
    - tag: grid
      header: 账号激活
      items:
        - text: 账号激活
          icon: authorize
          url: account-activate

        # - text: 密码重置
        #   icon: reset
        #   url: account-reset

    - media

    - official

    - info

    - tool

    - under-enroll

    - grad-enroll

    - tag: list
      items:
        - text: 登录开启海量校园功能
          url: account-login
      footer: " "

  at-school:
    - action

    - tag: grid
      header: 本科教务系统
      items:
        - text: 课程表
          icon: course-table
          url: course-table

        - text: 成绩查询
          icon: grade
          url: grade

        - text: 选课系统
          icon: select
          url: under-select

        - text: 考场查询
          icon: test
          url: exam-place

        - text: 专项考试成绩
          icon: test
          url: grade-special

        - text: 学籍注册查看
          icon: archive
          url: under-archive-view

        - text: 建立学籍
          icon: archive
          url: under-archive-create

        - text: 转专业计划
          icon: change
          url: change-major

        - text: 课程评价
          icon: heart
          url: under-commentary

    - media

    - official

    - info

    - tag: grid
      header: 账号相关
      items:
        - text: 账号激活
          icon: authorize
          url: account-activate

        - text: 校园邮箱邮件
          icon: email
          url: email-recent

        # - text: 密码重置
        #   icon: reset
        #   url: account-reset

        # - text: 邮箱申请
        #   icon: email
        #   url: email-apply

    - tool

    - under-enroll

    - grad-enroll

user:
  # []
  - tag: list
    items:
      - text: 使用指南
        icon: idea
        url: info?path=Oguide/

      - text: 更新日志
        icon: log
        url: info?path=Olog/

      - text: 隐私说明
        icon: privacy
        url: privacy

      - text: 关于
        icon: about
        url: about

  - tag: p
    heading: " "
    text:
      - 如果看过小程序后您还有疑问，欢迎加入 inNENU 咨询群 (1139044856) 进行咨询。
      - 小程序为 Mr.Hope 个人独自开发编写，现已花费 Mr.Hope 超 3300 小时，文字数量超过 108 万字，同时小程序服务器每年会产生开销。如果您觉得小程序很有帮助，欢迎您给予支持。
    style: "color: #888; font-size: 14px"

  - tag: functional-list
    items:
      - text: 分享小程序
        icon: share
        type: button
        openType: share

      - text: 查看 inNENU 微信视频号
        icon: wechat
        type: button
        handler: openChannel

      - text: 联系 Mr.Hope
        icon: contact
        type: button
        openType: contact
        handler: reportInfo

      - text: 评价小程序
        icon: star
        url: action?action=rate

about:
  - tag: list
    header: 小程序介绍
    items:
      - text: 小程序全部内容均由 Mr.Hope 独立开发。

      - text: 小程序现有字数为 1081042 字，其中东师指南部分 333362 字，新生迎新部分 105635 字，东师介绍部分 339460 字，机构介绍部分 70731 字，学院介绍部分 145237 字，功能大厅部分 38963 字，其他部分 47654 字。

      - text: Mr.Hope 个人介绍
        url: info?path=Oabout/mrhope

      - text: |-
          记: inNENU
        url: info?path=Oabout/history

      - text: 开发者访谈
        url: info?path=Oabout/interview

      - text: 常见问题
        url: info?path=Oabout/function

      - text: 致谢名单
        url: info?path=Oabout/thanks

  - tag: functional-list
    header: 支持小程序
    items:
      - text: 为保证小程序运行，每年购买维护服务器资源会产生开销。如果您希望帮助 Mr.Hope，欢迎联系 Mr.Hope 施以援手。

      - text: 联系 Mr.Hope
        icon: contact
        type: button
        openType: contact
        handler: reportInfo

  - tag: text
    heading: 小程序内容
    text:
      - 小程序页面内容仓库在 GitHub 上开源。如您愿意对小程序提供帮助，欢迎您点击下方链接为该仓库做贡献。您可以帮助扩充或编辑小程序的页面文字、图片以及相关文件。

  - tag: action
    content: https://github.com/inNENU/resource

  - tag: list
    header: 内容版权及使用
    items:
      - text: 请您特别注意，除标注来源的文字、图片 Mr.Hope 没有版权外，其余文字、图片均放置在『CC BY-NC-ND 4.0』协议下。请您合法使用这些文字与图片，以避免引起纠纷。

      - text: 协议详情
        url: info?path=Oabout/copyright

service:
  # 新版统一身份登录存在 Referrer 问题
  auth-init-info: online
  auth-init: online
  auth-login: online
  auth-captcha: online
  re-auth: online
  action-login: online
  auth-center-login: online
  my-login: online
  under-study-login: online
  under-system-login: online
  # 本科教务系统全部存在 Referrer 问题
  under-study-check: online
  under-commentary: online
  under-grade-detail: online
  under-grade-list: online
  under-special-exam: online
  under-select-category: online
  under-select-class: online
  under-select-info: online
  under-select-process: online
  under-select-search: online
  under-select-selected: online

notice:
  app:
    title: 遭受攻击通知
    content: 自 8 月 26 日 11:38 分起，小程序受到高频攻击，小程序昨日受到攻击后至 27 日 9:00 均运行缓慢并频发故障，现已恢复。

  main:
    title: 欢迎使用 inNENU
    content: 欢迎使用 inNENU。这是一个由 Mr.Hope 个人制作的非官方小程序，内含 108 万字的新生攻略。希望大家能够通过小程序摆脱对大学的迷茫。

  account-activate:
    title: 提示
    content: 如果你认为你输入了正确的信息但无法激活，请联系我校信息化办公室，电话 0431-85099005。
    force: true

  course-table:
    title: 暂未适配
    content: 请使用 weNENU 微信小程序查看新学期课表。

update:
  force: true
  reset: false
