main-page:
  guest: guest
  "2024": newcomer
  default: at-school

main-presets:
  guest:
    - tag: grid
      header: 您可能想关注
      items:
        - text: 学校概况
          color: red
          name: Description
          icon: about
          path: intro/about/

        - text: 学科建设
          color: olive
          name: Subject
          icon: content
          path: intro/subject/

        - text: 学生就业
          color: cyan
          name: Job
          icon: job
          path: intro/job/

        - text: 资助
          color: purple
          name: Subsidize
          icon: subsidize
          path: intro/subsidize/

        - text: 招生
          name: Enroll
          color: red
          icon: enroll
          path: intro/enroll/

        - text: 学院介绍
          name: School
          color: purple
          icon: school
          path: school/

        - text: 学校机构
          name: School
          color: red
          icon: apartment
          path: apartment/

        - text: 寝室
          color: blue
          name: Dorm
          icon: dorm
          path: guide/dorm/

        - text: 食堂
          color: orange
          name: Dining
          icon: dining
          path: guide/dining/

        - text: 快递
          color: olive
          name: Express
          icon: express
          path: guide/express/

        - text: 洗浴
          color: red
          name: Bath
          icon: bath
          path: guide/bath/

        - text: 生活
          color: purple
          name: Life
          icon: life
          path: guide/life/

        - text: 转专业
          color: red
          name: Change Major
          icon: change
          path: guide/change-major/

        - text: 师范生
          color: purple
          name: Normal
          icon: teacher
          path: guide/normal/

        - text: 课程
          color: orange
          name: Course
          icon: content
          path: guide/course/

        - text: 学习
          color: mauve
          name: Study
          icon: study
          path: guide/study/

        - text: 奖学金
          color: purple
          name: Scholarship
          icon: metal
          path: intro/scholarship/

        - text: 图书馆
          color: blue
          name: Library
          icon: library
          path: apartment/library/

        - text: 考研/保研
          color: red
          name: Postgraduate
          icon: study
          path: intro/grad/

  newcomer:
    - tag: grid
      header: 您可能想关注
      items:
        - text: 专业介绍
          color: mauve
          name: Major
          icon: study
          path: school/major

        - text: 寝室
          color: blue
          name: Dorm
          icon: dorm
          path: guide/dorm/

        - text: 食堂
          color: orange
          name: Dining
          icon: dining
          path: guide/dining/

        - text: 快递
          color: olive
          name: Express
          icon: express
          path: guide/express/

        - text: 洗浴
          color: red
          name: Bath
          icon: bath
          path: guide/bath/

        - text: 生活
          color: purple
          name: Life
          icon: life
          path: guide/life/

        - text: 转专业
          color: red
          name: Change Major
          icon: change
          path: guide/change-major/

        - text: 师范生
          color: purple
          name: Normal
          icon: teacher
          path: guide/normal/

        - text: 课程
          color: orange
          name: Course
          icon: content
          path: guide/course/

        - text: 学习
          color: mauve
          name: Study
          icon: study
          path: guide/study/

        - text: 奖学金
          color: purple
          name: Scholarship
          icon: metal
          path: intro/scholarship/

        - text: 校园地图
          color: orange
          name: Map
          icon: map
          url: map

        - text: 学校通知
          color: red
          name: Notice
          icon: notice
          url: notice-list

        - text: 学生组织
          color: blue
          name: Organization
          icon: student-org
          path: guide/org/

        - text: 社团
          color: orange
          name: Association
          icon: association
          path: guide/association/

        - text: 校园媒体
          color: grey
          name: Accounts
          icon: account
          url: school-media

      footer: 更多内容请详见下方其他 Tab 页

  at-school:
    - tag: grid
      header: 功能
      items:
        - text: 课程表
          color: grey
          name: Course
          icon: course-table
          url: course-table

        - text: 本科成绩查询
          color: orange
          name: Grade
          icon: grade
          url: under-grade

        - text: 学校通知
          color: red
          name: Notice
          icon: notice
          url: notice-list

        - text: 学校新闻
          color: cyan
          name: News
          icon: news
          url: notice-list?type=news

        - text: 校园邮箱
          color: purple
          name: Email
          icon: email
          url: email-recent

        - text: 图书馆
          color: purple
          name: Library
          icon: library
          url: library

        - text: 校历
          color: mauve
          name: Calendar
          icon: calendar
          url: calendar

        - text: 转专业计划
          color: red
          name: Change major
          icon: change
          url: change-major

      footer: 更多内容请详见下方其他 Tab 页

intro-page:
  guest:
    items:
      # - under-enroll
      # - grad-enroll
      - about
      # - school
    more:
      - apartment

  default:
    items:
      - about
      - school
      - apartment
    more:
      - under-enroll
      - grad-enroll

guide-page:
  guest:
    items:
      - newcomer
      - life
      - study
      - enjoy
    more:
      # - account
      # - service
      - tip
      - graduate

  "2024":
    items:
      - newcomer
      - life
      - study
      - enjoy
      - tip
    more:
      # - account
      # - service
      - graduate

  "2020":
    items:
      - graduate
      - study
      # - service
      # - account
    more:
      - life
      - tip
      - enjoy
      - newcomer

  default:
    items:
      # - service
      - study
      - life
    more:
      # - account
      - tip
      - enjoy
      - newcomer
      - graduate

function-page:
  guest: guest
  default: at-school

function-presets:
  guest:
    - tag: grid
      header: 账号激活
      items:
        - text: 账号激活
          color: grey
          name: Activate
          icon: authorize
          url: account-activate

    - tag: grid
      header: 东师风采
      items:
        - text: 校园地图
          color: orange
          name: Map
          icon: map
          url: map

        - text: 校园媒体
          color: grey
          name: Accounts
          icon: account
          url: school-media

    - tag: grid
      header: 信息查询
      items:
        - text: 校历
          color: olive
          name: Calendar
          icon: calendar
          url: calendar

        - text: 本科人才培养计划
          color: grey
          name: Cultivate
          icon: rule
          url: under-major-plan

        - text: 校史
          color: blue
          name: History
          icon: history
          url: calendar-history

        - text: 东师网站
          color: orange
          name: Websites
          icon: network
          url: website

        - text: 师大黄页
          color: purple
          name: Contact
          icon: phone
          url: phone

    - tag: grid
      header: 工具
      items:
        - text: 体测计算器
          color: olive
          name: PE Calculator
          icon: calculate
          url: pe-calculator

        - text: 东师天气
          color: purple
          name: Weather
          icon: sun
          url: weather

    - tag: grid
      header: 本科招生
      items:
        - text: 招生简章
          name: Rule
          color: blue
          icon: rule
          path: intro/enroll/under/rule/

        - text: 招生计划
          name: Plan
          color: orange
          icon: enroll
          url: under-enroll-plan

        - text: 历史分数
          name: History grade
          color: purple
          icon: time
          url: under-enroll-score

    - tag: list
      items:
        - text: 登录开启海量校园功能
          url: account-login
      footer: " "

  at-school:
    - tag: grid
      header: 融合门户
      items:
        - text: 学校通知
          color: red
          name: Notice
          icon: notice
          url: notice-list

        - text: 学校新闻
          color: cyan
          name: News
          icon: news
          url: notice-list?type=news

        - text: 图书馆
          color: purple
          name: Library
          icon: library
          url: library

    - tag: grid
      header: 本科教务系统
      items:
        - text: 课程表
          color: grey
          name: Course
          icon: course-table
          url: course-table

        - text: 本科成绩查询
          color: orange
          name: Grade
          icon: grade
          url: under-grade

        - text: 选课系统
          color: blue
          name: Select
          icon: select
          url: under-select

        - text: 考场查询
          color: grey
          name: Exam
          icon: test
          url: exam-place

        - text: 专项考试成绩
          color: red
          name: SpecialExam
          icon: test
          url: grade-special

        - text: 学籍注册查看
          color: purple
          name: Study Archive
          icon: archive
          url: under-archive-view

        - text: 建立学籍
          color: purple
          name: Create Archive
          icon: archive
          url: under-archive-create

        - text: 转专业计划
          color: red
          name: Change major
          icon: change
          url: change-major

        - text: 课程评价
          color: grey
          name: Commentary
          icon: heart
          url: under-commentary

    - tag: grid
      header: 东师风采
      items:
        - text: 校园地图
          color: orange
          name: Map
          icon: map
          url: map

        - text: 校园媒体
          color: grey
          name: Accounts
          icon: account
          url: school-media

    - tag: grid
      header: 信息查询
      items:
        - text: 校园邮箱邮件
          color: purple
          name: Email
          icon: email
          url: email-recent

        - text: 校历
          color: olive
          name: Calendar
          icon: calendar
          url: calendar

        - text: 东师网站
          color: orange
          name: Websites
          icon: network
          url: website

        - text: 师大黄页
          color: purple
          name: Contact
          icon: phone
          url: phone

    - tag: grid
      header: 账号相关
      items:
        - text: 账号激活
          color: grey
          name: Activate
          icon: authorize
          url: account-activate

        - text: 邮箱申请
          color: purple
          name: Email
          icon: email
          url: email-apply

    - tag: grid
      header: 工具
      items:
        - text: 体测计算器
          color: olive
          name: PE Calculator
          icon: calculate
          url: pe-calculator

        - text: 东师天气
          color: purple
          name: Weather
          icon: sun
          url: weather

      footer: " "

user:
  - tag: list
    items:
      - text: 使用指南
        icon: idea
        url: info?path=Oguide/

      - text: 更新日志
        icon: log
        url: info?path=Olog/

      - text: 隐私说明
        icon: privacy
        url: privacy

      - text: 关于
        icon: about
        url: about

  - tag: p
    heading: " "
    text:
      - 如果看过小程序后您还有疑问，欢迎加入 inNENU 咨询群 (1139044856) 进行咨询。
      - 小程序为 Mr.Hope 个人独自开发编写，现已花费 Mr.Hope 超 3300 小时，文字数量超过 108 万字。
    style: "color: #888; font-size: 14px"

  - tag: functional-list
    items:
      - text: 分享小程序
        icon: share
        type: button
        openType: share

      - text: 加入 inNENU 咨询群
        icon: qq-group
        type: button
        openType: openGroupProfile
        groupId: "1139044856"

      - text: 加入东北师大频道
        icon: qq-group
        type: button
        openType: openGuildProfile
        guildId: "5684461640601496"

      - text: 添加到桌面
        icon: send
        type: button
        handler: addToDesktop

about:
  - tag: list
    header: 小程序介绍
    items:
      - text: 小程序全部内容均由 Mr.Hope 独立开发。

      - text: 小程序现有字数为 1081582 字，其中东师指南部分 333570 字，新生迎新部分 105560 字，东师介绍部分 339481 字，机构介绍部分 70763 字，学院介绍部分 145359 字，功能大厅部分 39222 字，其他部分 47627 字。

      - text: Mr.Hope 个人介绍
        url: info?path=Oabout/mrhope

      - text: |-
          记: inNENU
        url: info?path=Oabout/history

      - text: 开发者访谈
        url: info?path=Oabout/interview

      - text: 常见问题
        url: info?path=Oabout/function

      - text: 致谢名单
        url: info?path=Oabout/thanks

  - tag: text
    heading: 小程序内容
    text:
      - 小程序页面内容仓库在 GitHub 上开源。如您愿意对小程序提供帮助，欢迎您点击下方链接为该仓库做贡献。您可以帮助扩充或编辑小程序的页面文字、图片以及相关文件。

  - tag: action
    content: https://github.com/inNENU/resource

  - tag: list
    header: 内容版权及使用
    items:
      - text: 请您特别注意，除标注来源的文字、图片 Mr.Hope 没有版权外，其余文字、图片均放置在『CC BY-NC-ND 4.0』协议下。请您合法使用这些文字与图片，以避免引起纠纷。

      - text: 协议详情
        url: info?path=Oabout/copyright

service:
  # grad-system-login: online
  # under-study-check: online
  # under-commentary: online
  # under-grade-detail: online
  # under-grade-list: online
  # under-special-exam: online
  # under-select-category: online
  # under-select-class: online
  # under-select-info: online
  # under-select-process: online
  # under-select-search: online
  # under-select-selected: online
  forceOnline: true

notice:
  main:
    title: 欢迎使用 inNENU
    content: 欢迎使用 inNENU。这是一个由 Mr.Hope 个人制作的非官方小程序，内含 108 万字的新生攻略。希望大家能够通过小程序摆脱对大学的迷茫。

  account-activate:
    title: 2024级本科生账号暂不可激活
    content: 由于本科生尚未完成录取，2024年新生统一身份认证账户暂不可激活。根据去年经验，预计开放时间不早于 2024 年 8 月。请耐心等待官方正式通知。
    # title: 手机验证码
    # content: 学校的短信验证服务发送验证码有较高延迟，请耐心等待。另外部分手机号可能收不到验证码，遇到此情况可更换家人号码尝试激活。

  under-select:
    title: 公测中
    content: 新版本科选课系统已初步适配，现面向全体用户发起公测。特别提示：当前选课系统已完整内测阶段，所需功能基本可用，但 Mr.Hope 不保证当前公测版系统没有问题，也不会对公测版系统引发的问题负责。继续使用即代表您已知晓并接受此风险。
    force: true

update:
  force: true
  reset: false
