title: 城乡居民基本医疗保险
icon: insurance
author: Mr.Hope
time: 2024-08-29T09:00:55.764Z
shareable: true
content:
  - tag: text
    type: info
    text:
      - 学校每年都会组织学生办理“长春市城乡居民基本医疗保险”。

  - tag: title
    text: 简介

  - tag: p
    text: 城镇居民基本医疗保险是社会医疗保险的组成部分，采取以政府为主导，以居民个人 (家庭) 缴费为主，政府适度补助为辅的筹资方式，按照缴费标准和待遇水平相一致的原则，为城镇居民提供医疗需求的医疗保险制度。

  - tag: text
    type: tip
    text:
      - 入校前已缴纳的城乡居民基本医疗保险的结束时间为入学年底，所以无需担心保险的断缴问题。
      - 所以学校在 10 月后才会开展保险的统计、信息录入和收缴工作。

  - tag: text
    type: info
    heading: 缴纳地点
    text:
      - 参保学生需拥有教育部门登记在册的学籍。
      - 吉林省范围内的全日制在籍学生统一在学籍地参保。
      - 在籍学生为经省内各地县 (市、区)级民政或乡村振兴部门认定的符合参保资助条件的困难人员可选择在身仹认定地参保缴费，直接享受参保地相关的待遇政策。如选择在居住地或学籍地参保，按普通居民或学生身份享受参保地相关待遇，其参保资劣及直接医疗救劣等保障待遇到身份认定地医保部门申请享受。
      - 若参保学生为省外民政或乡村振兴部门认定的符合参保资助条件的困难人员 ，可选择在认定地参保，享受参保地相关待遇政策；如选择在学籍地 (吉林省内) 参保，全额缴纳年度个人医保费后，可享受吉林省普通居民 (学生) 医保待遇。

  - tag: title
    text: 信息录入

  - tag: p
    text:
      - 保险信息录入由各辅导员负责，通过学校与医保局进行联系，将学生保险经办机构改为“长春市市本级社会医疗保险管理局”。

  - tag: title
    text: 缴费标准

  - tag: text
    type: info
    heading: 2023 年度收费标准
    text:
      - 320 元/人/年

  - tag: text
    text: 关于缴费详情，请见

  - tag: list
    header: false
    items:
      - text: 缴费详情
        icon: money
        path: base-pay

  - tag: title
    text: 保险生效时间

  - tag: ul
    heading: 2023 年度城乡居民基本医疗保险
    text:
      - 在集中预缴费期内缴纳个人医保费的参保人员 (含新参保人员) ，享受 2023 年 1 月 1 日至 2023 年 12 月 31 日一个自然年度的医保待遇。
      - 在集中预缴费期外补缴个人医保费的参保人员 (含新参保人员) ，医保部门将设置 3 个月的等待期，等待期内不享受医保待遇。

  - tag: title
    text: 保险报销

  - tag: text
    type: info
    heading: 请参见长春市城乡居民基本医疗保险报销
    path: reimburse
