main-page:
  guest: guest
  "2024": newcomer
  default: at-school

main-presets:
  guest:
    - tag: card
      cover: $img/tab/stream.png
      title: 经验分享与答疑
      path: newcomer/activity/streaming

    - tag: card
      cover: $img/tab/faq.png
      title: 常见问题
      path: newcomer/faq/

    - tag: grid
      header: 您可能想关注
      items:
        - text: 高考录取查询
          name: Admission
          color: cyan
          icon: letter
          url: admission?type=search

        - text: 找到组织
          color: olive
          name: Contact
          icon: qq-group
          path: newcomer/contact/

        - text: 学校概况
          color: red
          name: Description
          icon: about
          path: intro/about/

        - text: 学科建设
          color: olive
          name: Subject
          icon: content
          path: intro/subject/

        - text: 学生就业
          color: cyan
          name: Job
          icon: job
          path: intro/job/

        - text: 资助
          color: purple
          name: Subsidize
          icon: subsidize
          path: intro/subsidize/

        - text: 招生
          name: Enroll
          color: red
          icon: enroll
          path: intro/enroll/

        - text: 学院介绍
          name: School
          color: purple
          icon: school
          path: school/

        - text: 学校机构
          name: School
          color: red
          icon: apartment
          path: apartment/

        - text: 寝室
          color: blue
          name: Dorm
          icon: dorm
          path: guide/dorm/

        - text: 食堂
          color: orange
          name: Dining
          icon: dining
          path: guide/dining/

        - text: 洗浴
          color: red
          name: Bath
          icon: bath
          path: guide/bath/

        - text: 生活
          color: purple
          name: Life
          icon: life
          path: guide/life/

        - text: 转专业
          color: red
          name: Change Major
          icon: change
          path: guide/change-major/

        - text: 师范生
          color: purple
          name: Normal
          icon: teacher
          path: guide/normal/

        - text: 课程
          color: orange
          name: Course
          icon: content
          path: guide/course/

        - text: 学习
          color: mauve
          name: Study
          icon: study
          path: guide/study/

        - text: 奖学金
          color: purple
          name: Scholarship
          icon: metal
          path: intro/scholarship/

        - text: 图书馆
          color: blue
          name: Library
          icon: library
          path: apartment/library/

        - text: 考研/保研
          color: red
          name: Postgraduate
          icon: study
          path: intro/grad/

  newcomer:
    - tag: grid
      header: 您可能想关注
      items:
        - text: 找到组织
          color: olive
          name: Contact
          icon: qq-group
          path: newcomer/contact/

        - text: 专业介绍
          color: mauve
          name: Major
          icon: study
          path: school/major

        - text: 寝室
          color: blue
          name: Dorm
          icon: dorm
          path: guide/dorm/

        - text: 食堂
          color: orange
          name: Dining
          icon: dining
          path: guide/dining/

        - text: 洗浴
          color: red
          name: Bath
          icon: bath
          path: guide/bath/

        - text: 生活
          color: purple
          name: Life
          icon: life
          path: guide/life/

        - text: 转专业
          color: red
          name: Change Major
          icon: change
          path: guide/change-major/

        - text: 师范生
          color: purple
          name: Normal
          icon: teacher
          path: guide/normal/

        - text: 课程
          color: orange
          name: Course
          icon: content
          path: guide/course/

        - text: 学习
          color: mauve
          name: Study
          icon: study
          path: guide/study/

        - text: 奖学金
          color: purple
          name: Scholarship
          icon: metal
          path: intro/scholarship/

        - text: 校园地图
          color: orange
          name: Map
          icon: map
          url: map

        - text: 学校通知
          color: red
          name: Notice
          icon: notice
          url: notice-list

        - text: 学生组织
          color: blue
          name: Organization
          icon: student-org
          path: guide/org/

        - text: 社团
          color: orange
          name: Association
          icon: association
          path: guide/association/

        - text: 校园媒体
          color: grey
          name: Accounts
          icon: account
          url: school-media

      footer: 更多内容请详见下方其他 Tab 页

  at-school:
    - tag: grid
      header: 功能
      items:
        - text: 课程表
          color: grey
          name: Course
          icon: course-table
          url: course-table

        - text: 成绩查询
          color: orange
          name: Grade
          icon: grade
          url: grade

        - text: 学校通知
          color: red
          name: Notice
          icon: notice
          url: notice-list

        - text: 学校新闻
          color: cyan
          name: News
          icon: news
          url: notice-list?type=news

        - text: 校园邮箱
          color: purple
          name: Email
          icon: email
          url: email-recent

        - text: 图书馆
          color: purple
          name: Library
          icon: library
          url: library

        - text: 校历
          color: mauve
          name: Calendar
          icon: calendar
          url: calendar

        - text: 转专业计划
          color: red
          name: Change major
          icon: change
          url: change-major

      footer: 更多内容请详见下方其他 Tab 页

intro-page:
  guest:
    items:
      - under-enroll
      - grad-enroll
      - about
      - school
    more:
      - apartment

  default:
    items:
      - about
      - school
      - apartment
    more:
      - under-enroll
      - grad-enroll

guide-page:
  guest:
    items:
      - newcomer
      - life
      - study
      - enjoy
    more:
      - account
      - service
      - tip
      - graduate

  "2024":
    items:
      - newcomer
      - life
      - study
      - enjoy
      - tip
    more:
      - account
      - service
      - graduate

  "2020":
    items:
      - graduate
      - study
      - service
      - account
    more:
      - life
      - tip
      - enjoy
      - newcomer

  default:
    items:
      - service
      - study
      - life
    more:
      - account
      - tip
      - enjoy
      - newcomer
      - graduate

function-page:
  guest: guest
  default: at-school

function-presets:
  guest:
    - tag: grid
      header: 账号激活
      items:
        - text: 账号激活
          color: grey
          name: Activate
          icon: authorize
          url: account-activate

        - text: 密码重置
          color: grey
          name: Reset
          icon: reset
          url: account-reset

    - tag: grid
      header: 东师风采
      items:
        - text: 校园地图
          color: orange
          name: Map
          icon: map
          url: map

        - text: 音悦东师
          color: blue
          name: Music
          icon: cd
          url: music

        - text: 影约东师
          color: mauve
          name: Media
          icon: media
          url: video?type=video

        - text: 校园媒体
          color: grey
          name: Accounts
          icon: account
          url: school-media

    - tag: grid
      header: 学校动态
      items:
        - text: 通知公告
          color: red
          name: Notice
          icon: notice
          url: official-notice-list

        - text: 要闻速递
          color: cyan
          name: News
          icon: news
          url: official-info-list?type=news

        - text: 媒体师大
          color: cyan
          name: Media
          icon: media
          url: official-info-list?type=media

        - text: 人文社科
          color: cyan
          name: Social
          icon: marx
          url: official-info-list?type=social

        - text: 自然科学
          color: cyan
          name: Science
          icon: chemistry
          url: official-info-list?type=science

        - text: 学术预告
          color: cyan
          name: News
          icon: study
          url: official-academic-list

    - tag: grid
      header: 信息查询
      items:
        - text: 校历
          color: olive
          name: Calendar
          icon: calendar
          url: calendar

        - text: 本科人才培养计划
          color: grey
          name: Cultivate
          icon: rule
          url: under-major-plan

        - text: 校史
          color: blue
          name: History
          icon: history
          url: calendar-history

        - text: 东师网站
          color: orange
          name: Websites
          icon: network
          url: website

        - text: 师大黄页
          color: purple
          name: Contact
          icon: phone
          url: phone

    - tag: grid
      header: 工具
      items:
        - text: 体测计算器
          color: olive
          name: PE Calculator
          icon: calculate
          url: pe-calculator

        - text: 东师天气
          color: purple
          name: Weather
          icon: sun
          url: weather

    - tag: grid
      header: 本科招生
      items:
        - text: 招生简章
          name: Rule
          color: blue
          icon: rule
          path: intro/enroll/under/rule/

        - text: 招生计划
          name: Plan
          color: orange
          icon: enroll
          url: under-enroll-plan

        - text: 历史分数
          name: History grade
          color: purple
          icon: time
          url: under-enroll-score

    - tag: list
      items:
        - text: 登录开启海量校园功能
          url: account-login
      footer: " "

  at-school:
    - tag: grid
      header: 融合门户
      items:
        - text: 学校通知
          color: red
          name: Notice
          icon: notice
          url: notice-list

        - text: 学校新闻
          color: cyan
          name: News
          icon: news
          url: notice-list?type=news

        - text: 图书馆
          color: purple
          name: Library
          icon: library
          url: library

    - tag: grid
      header: 教务系统
      items:
        - text: 课程表
          color: grey
          name: Course
          icon: course-table
          url: course-table

        - text: 成绩查询
          color: orange
          name: Grade
          icon: grade
          url: grade

        - text: 选课系统
          color: blue
          name: Select
          icon: select
          url: under-select

        - text: 考场查询
          color: grey
          name: Exam
          icon: test
          url: exam-place

        - text: 专项考试成绩
          color: red
          name: SpecialExam
          icon: test
          url: grade-special

        - text: 学籍注册查看
          color: purple
          name: Study Archive
          icon: archive
          url: under-archive-view

        - text: 建立学籍
          color: purple
          name: Create Archive
          icon: archive
          url: under-archive-create

        - text: 转专业计划
          color: red
          name: Change major
          icon: change
          url: change-major

        - text: 课程评价
          color: grey
          name: Commentary
          icon: heart
          url: under-commentary

    - tag: grid
      header: 东师风采
      items:
        - text: 校园地图
          color: orange
          name: Map
          icon: map
          url: map

        - text: 音悦东师
          color: blue
          name: Music
          icon: cd
          url: music

        - text: 影约东师
          color: mauve
          name: Media
          icon: media
          url: video?type=video

        - text: 校园媒体
          color: grey
          name: Accounts
          icon: account
          url: school-media

    - tag: grid
      header: 学校动态
      items:
        - text: 通知公告
          color: red
          name: Notice
          icon: notice
          url: official-notice-list

        - text: 要闻速递
          color: cyan
          name: News
          icon: news
          url: official-info-list?type=news

        - text: 媒体师大
          color: cyan
          name: Media
          icon: media
          url: official-info-list?type=media

        - text: 人文社科
          color: cyan
          name: Social
          icon: marx
          url: official-info-list?type=social

        - text: 自然科学
          color: cyan
          name: Science
          icon: chemistry
          url: official-info-list?type=science

        - text: 学术预告
          color: cyan
          name: News
          icon: study
          url: official-academic-list

    - tag: grid
      header: 信息查询
      items:
        - text: 校园邮箱邮件
          color: purple
          name: Email
          icon: email
          url: email-recent

        - text: 校历
          color: olive
          name: Calendar
          icon: calendar
          url: calendar

        - text: 校外服务
          color: red
          name: Service
          icon: contact
          url: info?path=/other/action/out

        - text: 东师网站
          color: orange
          name: Websites
          icon: network
          url: website

        - text: 师大黄页
          color: purple
          name: Contact
          icon: phone
          url: phone

    - tag: grid
      header: 账号相关
      items:
        - text: 账号激活
          color: grey
          name: Activate
          icon: authorize
          url: account-activate

        - text: 密码重置
          color: grey
          name: Reset
          icon: reset
          url: account-reset

        - text: 邮箱申请
          color: purple
          name: Email
          icon: email
          url: email-apply

    - tag: grid
      header: 管理系统
      items:
        - text: 统一身份认证
          color: blue
          name: Authorize
          icon: account
          url: web?url=https://authserver.nenu.edu.cn/authserver/login

        - text: 网上服务大厅
          color: cyan
          name: MyNenu
          icon: network
          url: web?url=http://my.nenu.edu.cn/

        - text: 故障报修
          color: purple
          name: Repair
          icon: repair
          url: web?url=http://gyglxt.nenu.edu.cn/repair/redirect/website/index

        - text: 宿舍系统
          color: grey
          name: Dorm
          icon: system
          url: web?url=http://gyglxt.nenu.edu.cn/?sid=http://gyglxt.nenu.edu.cn

    - tag: grid
      header: 工具
      items:
        - text: 体测计算器
          color: olive
          name: PE Calculator
          icon: calculate
          url: pe-calculator

        - text: 东师天气
          color: purple
          name: Weather
          icon: sun
          url: weather

      footer: " "

user:
  - tag: list
    items:
      - text: 使用指南
        icon: idea
        url: info?path=Oguide/

      - text: 更新日志
        icon: log
        url: info?path=Olog/

      - text: 隐私说明
        icon: privacy
        url: privacy

      - text: 关于
        icon: about
        url: about

  - tag: text
    heading: " "
    text:
      - 如果看过 App 后您还有疑问，欢迎加入 inNENU 咨询群 (1139044856) 进行咨询。
      - App 为 Mr.Hope 个人独自开发编写，现已花费 Mr.Hope 超 3000 小时，文字数量超过 108 万字，同时 App 服务器每年会产生开销。如果您觉得 App 很有帮助，欢迎您给予支持。
    style: "color: #888; font-size: 14px"

about:
  - tag: list
    header: 小程序介绍
    items:
      - text: 小程序全部内容均由 Mr.Hope 独立开发。

      - text: 小程序现有字数为 1080171 字，其中东师指南部分 335216 字，新生迎新部分 102295 字，东师介绍部分 339466 字，机构介绍部分 70759 字，学院介绍部分 145318 字，功能大厅部分 39496 字，其他部分 47621 字。

      # - text: Hope Studio 介绍
      #   url: info?path=Ohope-studio/about

      - text: Mr.Hope 个人介绍
        url: info?path=Oabout/mrhope

      - text: |-
          记: inNENU
        url: info?path=Oabout/history

      - text: 开发者访谈
        url: info?path=Oabout/interview

      - text: 常见问题
        url: info?path=Oabout/function

      - text: 致谢名单
        url: info?path=Oabout/thanks

  - tag: functional-list
    header: 支持小程序
    items:
      - text: 为保证小程序运行，每年购买维护服务器资源会产生开销。如果您希望帮助 Mr.Hope，欢迎联系 Mr.Hope 施以援手。

      - text: 联系 Mr.Hope
        icon: contact
        type: button
        openType: contact
        handler: reportInfo

  - tag: text
    heading: 小程序内容
    text:
      - 小程序页面内容仓库在 GitHub 上开源。如您愿意对小程序提供帮助，欢迎您点击下方链接为该仓库做贡献。您可以帮助扩充或编辑小程序的页面文字、图片以及相关文件。

  - tag: action
    content: https://github.com/inNENU/resource

  - tag: list
    header: 内容版权及使用
    items:
      - text: 请您特别注意，除标注来源的文字、图片 Mr.Hope 没有版权外，其余文字、图片均放置在『CC BY-NC-ND 4.0』协议下。请您合法使用这些文字与图片，以避免引起纠纷。

      - text: 协议详情
        url: info?path=Oabout/copyright

service:
  # 新版统一身份登录存在 Referrer 问题
  auth-init-info: online
  auth-init: online
  auth-login: online
  auth-captcha: online
  auth-center-login: online
  re-auth: online
  action-login: online
  my-login: online
  under-study-login: online
  under-system-login: online
  # 本科教务系统全部存在 Referrer 问题
  under-study-check: online
  under-commentary: online
  under-grade-detail: online
  under-grade-list: online
  under-special-exam: online
  under-select-category: online
  under-select-class: online
  under-select-info: online
  under-select-process: online
  under-select-search: online
  under-select-selected: online

notice:
  main:
    title: 欢迎使用 inNENU
    content: 欢迎使用 inNENU。这是一个由 Mr.Hope 个人制作的非官方小程序，内含 108 万字的新生攻略。希望大家能够通过小程序摆脱对大学的迷茫。

  account-activate:
    title: 2024级本科生账号暂不可激活
    content: 研究生目前可以激活账户，本科生需等到 8 月 10 日信息录入后方可激活，请耐心等待。
    force: true

update:
  force: false
  reset: false
