action:
  tag: grid
  header: 融合门户
  items:
    - text: 学校通知
      icon: notice
      url: notice-list

    - text: 学校新闻
      icon: news
      url: notice-list?type=news

    - text: 图书馆
      icon: library
      url: library

official:
  tag: grid
  header: 学校动态
  items:
    - text: 通知公告
      icon: notice
      url: official-notice-list

    - text: 要闻速递
      icon: news
      url: official-info-list?type=news

    - text: 媒体师大
      icon: media
      url: official-info-list?type=media

    - text: 人文社科
      icon: marx
      url: official-info-list?type=social

    - text: 自然科学
      icon: chemistry
      url: official-info-list?type=science

    - text: 学术预告
      icon: study
      url: official-academic-list

media:
  tag: grid
  header: 东师风采
  items:
    - text: 校园地图
      icon: map
      url: map

    - text: 音悦东师
      icon: cd
      url: music

    - text: 影约东师
      icon: media
      url: video?type=video

    - text: 校园媒体
      icon: account
      url: school-media

info:
  tag: grid
  header: 信息查询
  items:
    - calendar
    - under-major-plan
    - website
    - phone
    - calendar-history

tool:
  tag: grid
  header: 工具
  items:
    - pe-calculator
    - weather

grad-enroll:
  tag: grid
  header: 研究生招生
  items:
    - text: 招生简章
      icon: rule
      path: intro/enroll/grad/rule/

    - text: 招生计划
      icon: enroll
      url: grad-enroll-plan

    - text: 推免计划
      icon: time
      url: grad-enroll-plan?recommend=true

under-enroll:
  tag: grid
  header: 本科招生
  items:
    - admission

    - text: 招生简章
      icon: rule
      path: intro/enroll/under/rule/

    - text: 招生计划
      icon: enroll
      url: under-enroll-plan

    - text: 历史分数
      icon: time
      url: under-enroll-score
