main-page:
  guest: guest
  "2024": newcomer
  default: at-school

main-presets:
  guest:
    - tag: card
      cover: $img/tab/activate.jpg
      title: 账号激活
      url: account-activate

    - tag: card
      cover: $img/tab/faq.png
      title: 常见问题
      path: newcomer/faq/

    # - tag: card
    #   cover: $img/tab/stream.png
    #   title: 经验分享与答疑
    #   path: newcomer/activity/streaming

    - tag: grid
      header: 您可能想关注
      items:
        - text: 学校概况
          icon: about
          path: intro/about/

        - text: 学科建设
          icon: content
          path: intro/subject/

        - text: 学生就业
          icon: job
          path: intro/job/

        - text: 资助
          icon: subsidize
          path: intro/subsidize/

        - text: 招生
          icon: enroll
          path: intro/enroll/

        - text: 学院介绍
          icon: school
          path: school/

        - text: 学校机构
          icon: apartment
          path: apartment/

        - text: 寝室
          icon: dorm
          path: guide/dorm/

        - text: 食堂
          icon: dining
          path: guide/dining/

        - text: 快递
          icon: express
          path: guide/express/

        - text: 洗浴
          icon: bath
          path: guide/bath/

        - text: 生活
          icon: life
          path: guide/life/

        - text: 转专业
          icon: change
          path: guide/change-major/

        - text: 师范生
          icon: teacher
          path: guide/normal/

        - text: 课程
          icon: content
          path: guide/course/

        - text: 学习
          icon: study
          path: guide/study/

        - text: 奖学金
          icon: metal
          path: intro/scholarship/

        - text: 图书馆
          icon: library
          path: apartment/library/

        - text: 考研/保研
          icon: study
          path: intro/grad/

  newcomer:
    - tag: grid
      header: 您可能想关注
      items:
        - text: 专业介绍
          icon: study
          path: school/major

        - text: 寝室
          icon: dorm
          path: guide/dorm/

        - text: 食堂
          icon: dining
          path: guide/dining/

        - text: 快递
          icon: express
          path: guide/express/

        - text: 洗浴
          icon: bath
          path: guide/bath/

        - text: 生活
          icon: life
          path: guide/life/

        - text: 转专业
          icon: change
          path: guide/change-major/

        - text: 师范生
          icon: teacher
          path: guide/normal/

        - text: 课程
          icon: content
          path: guide/course/

        - text: 学习
          icon: study
          path: guide/study/

        - text: 奖学金
          icon: metal
          path: intro/scholarship/

        - text: 校园地图
          icon: map
          url: map

        - text: 学校通知
          icon: notice
          url: notice-list

        - text: 学生组织
          icon: student-org
          path: guide/org/

        - text: 社团
          icon: association
          path: guide/association/

        - text: 校园媒体
          icon: account
          url: school-media

      footer: 更多内容请详见下方其他 Tab 页

  at-school:
    - tag: grid
      header: 功能
      items:
        - text: 课程表
          icon: course-table
          url: under-course-table

        - text: 成绩查询
          icon: grade
          url: under-grade

        - text: 学校通知
          icon: notice
          url: notice-list

        - text: 学校新闻
          icon: news
          url: notice-list?type=news

        - text: 校园邮箱
          icon: email
          url: email-recent

        - text: 图书馆
          icon: library
          url: library

        - text: 校历
          icon: calendar
          url: calendar

        - text: 转专业计划
          icon: change
          url: change-major

      footer: 更多内容请详见下方其他 Tab 页

intro-page:
  guest:
    items:
      - under-enroll
      - grad-enroll
      - about
      - school
    more:
      - apartment

  default:
    items:
      - about
      - school
      - apartment
    more:
      - under-enroll
      - grad-enroll

guide-page:
  guest:
    items:
      - newcomer
      - life
      - study
      - enjoy
      - normal
    more:
      - account
      - service
      - tip
      - graduate

  "2024":
    items:
      - newcomer
      - life
      - study
      - normal
      - enjoy
      - service
      - account
      - tip
    more:
      - graduate

  "2020":
    items:
      - graduate
      - study
      - service
      - account
    more:
      - life
      - tip
      - enjoy
      - newcomer

  default:
    items:
      - service
      - study
      - life
      - account
    more:
      - normal
      - tip
      - enjoy
      - newcomer
      - graduate

function-page:
  guest: guest
  default: at-school

function-presets:
  guest:
    - tag: grid
      header: 账号激活
      items:
        - text: 账号激活
          icon: authorize
          url: account-activate

        # - text: 密码重置
        #   icon: reset
        #   url: account-reset

    - media

    - official

    - info

    - tool

    - under-enroll

    - grad-enroll

    - tag: list
      items:
        - text: 登录开启海量校园功能
          url: account-login
      footer: " "

  at-school:
    - action

    - tag: grid
      header: 本科教务系统
      items:
        - text: 课程表
          icon: course-table
          url: under-course-table

        - text: 成绩查询
          icon: grade
          url: under-grade

        - text: 选课系统
          icon: select
          url: under-select

        - text: 考场查询
          icon: test
          url: exam-place

        - text: 专项考试成绩
          icon: test
          url: under-grade-special

        - text: 学籍注册查看
          icon: archive
          url: under-archive-view

        # - text: 建立学籍
        #   icon: archive
        #   url: under-archive-create

        - text: 转专业计划
          icon: change
          url: change-major

        - text: 课程评价
          icon: heart
          url: under-commentary

    - media

    - official

    - info

    - tag: grid
      header: 账号相关
      items:
        - text: 账号激活
          icon: authorize
          url: account-activate

        - text: 校园邮箱邮件
          icon: email
          url: email-recent

        - text: 校外服务
          icon: contact
          url: info?path=/other/action/out

        # - text: 密码重置
        #   icon: reset
        #   url: account-reset

        # - text: 邮箱申请
        #   icon: email
        #   url: email-apply

    - tag: grid
      header: 管理系统
      items:
        - text: 统一身份认证
          icon: account
          url: web?url=https://authserver.nenu.edu.cn/authserver/login

        - text: 网上服务大厅
          icon: network
          url: web?url=http://my.nenu.edu.cn/

        - text: 故障报修
          icon: repair
          url: web?url=http://gyglxt.nenu.edu.cn/repair/redirect/website/index

        - text: 宿舍系统
          icon: system
          url: web?url=http://gyglxt.nenu.edu.cn/?sid=http://gyglxt.nenu.edu.cn

    - tool

    - under-enroll

    - grad-enroll

user:
  - tag: list
    items:
      - text: 使用指南
        icon: idea
        url: info?path=Oguide/

      - text: 更新日志
        icon: log
        url: info?path=Olog/

      - text: 隐私说明
        icon: privacy
        url: privacy

      - text: 关于
        icon: about
        url: about

  - tag: p
    header: " "
    text:
      - 如果看过 App 后您还有疑问，欢迎加入 inNENU 咨询群 (1139044856) 进行咨询。
      - App 为 Mr.Hope 个人独自开发编写，现已花费 Mr.Hope 超 3300 小时，文字数量超过 108 万字，同时 App 服务器每年会产生开销。如果您觉得 App 很有帮助，欢迎您给予支持。
    style: "color: #888; font-size: 14px"

about:
  - tag: list
    header: App 介绍
    items:
      - text: App 全部内容均由 Mr.Hope 独立开发。

      - text: App 现有字数为 1043135 字，其中东师指南部分 330611 字，新生迎新部分 90372 字，东师介绍部分 339346 字，机构介绍部分 58671 字，学院介绍部分 138569 字，功能大厅部分 38218 字，其他部分 47348 字。

      - text: Mr.Hope 个人介绍
        url: info?path=Oabout/mrhope

      - text: |-
          记: inNENU
        url: info?path=Oabout/history

      - text: 开发者访谈
        url: info?path=Oabout/interview

      - text: 常见问题
        url: info?path=Oabout/function

      - text: 致谢名单
        url: info?path=Oabout/thanks

  - tag: functional-list
    header: 支持 App
    items:
      - text: 为保证 App 运行，每年购买维护服务器资源会产生开销。如果您希望帮助 Mr.Hope，欢迎联系 Mr.Hope 施以援手。

      - text: 联系 Mr.Hope
        icon: contact
        type: button
        openType: contact
        handler: reportInfo

  - tag: text
    header: App 内容
    text:
      - App 页面内容仓库在 GitHub 上开源。如您愿意对 App 提供帮助，欢迎您点击下方链接为该仓库做贡献。您可以帮助扩充或编辑 App 的页面文字、图片以及相关文件。

  - tag: action
    content: https://github.com/inNENU/resource

  - tag: list
    header: 内容版权及使用
    items:
      - text: 请您特别注意，除标注来源的文字、图片 Mr.Hope 没有版权外，其余文字、图片均放置在『CC BY-NC-ND 4.0』协议下。请您合法使用这些文字与图片，以避免引起纠纷。

      - text: 协议详情
        url: info?path=Oabout/copyright

service:
  # 新版统一身份登录存在 Referrer 问题
  auth-init-info: online
  auth-init: online
  auth-login: online
  auth-captcha: online
  re-auth: online
  action-login: online
  auth-center-login: online
  my-login: online
  under-study-login: online
  under-system-login: online
  # 本科教务系统全部存在 Referrer 问题
  under-study-check: online
  under-commentary: online
  under-grade-detail: online
  under-grade-list: online
  under-special-exam: online
  under-select-category: online
  under-select-class: online
  under-select-info: online
  under-select-process: online
  under-select-search: online
  under-select-selected: online

notice:
  app:
    title: 遭受攻击通知
    content: 自 8 月 26 日 11:38 分起，App 受到高频攻击，App 昨日受到攻击后至 27 日 9:00 均运行缓慢并频发故障，现已恢复。

  main:
    title: 欢迎使用 inNENU
    content: 欢迎使用 inNENU。这是一个由 Mr.Hope 个人制作的非官方App，内含 108 万字的新生攻略。希望大家能够通过 App 摆脱对大学的迷茫。

  account-activate:
    title: 提示
    content: 如果你认为你输入了正确的信息但无法激活，请联系我校信息化办公室，电话 0431-85099005。
    force: true

update:
  force: false
  reset: false
