# 上次更新于 9/25 16:30
all: 3200
donations:
  - - MING
    - 1.42
  - - v
    - 2
  - - 多多动脑
    - 2
  - - 快乐打工人
    - 4
  - - 海鲜面
    - 2
  - - 有石名黛
    - 4
  - - 庚
    - 6
  - - 好名
    - 2
  - - lisa
    - 8
  - - 一头糖醋蒜
    - 2
  - - 赜琦
    - 2
  - - zzzzlz
    - 4
  - - 永远Karl
    - 2
  - - 最喜欢倩倩姐姐啦~
    - 2
  - - D6
    - 2
  - - "[未知用户名]"
    - 8
  - - 栖
    - 2
  - - CLARA
    - 2
  - - 小町
    - 2
  - - 阴暗军训预备役之火辣B格
    - 24
  - - 行者有疆
    - 4
  - - 王执中
    - 2
  - - 🐏🐏🐏
    - 4
  - - 绫光phlyer
    - 2
  - - 欧比旺克诺比
    - 6
  - - 璎珞朵朵
    - 18
  - - 小碧心
    - 2
  - - Giselle
    - 2
  - - 来年
    - 2
  - - 杨硕
    - 8
  - - 苍绿
    - 6
  - - 莉
    - 8
  - - ='人'=
    - 8
  - - 肚肚(；\O/)o
    - 4
  - - 日不落行秋
    - 2
  - - 肖春梅
    - 2
  - - 🍭🍀不倒翁🍀🍭
    - 20
  - - D6
    - 6
  - - 波
    - 2
  - - Creep
    - 1
  - - 虿
    - 2
  - - 认识你自己
    - 12
  - - 涵
    - 2
  - - (日文实在打不出来.....)
    - 2
  - - Juliet
    - 1
  - - 拾酒
    - 2
  - - cka
    - 2
  - - 小孩
    - 2
  - - Mononoke
    - 2
  - - 马非马
    - 2
  - - Wave
    - 2
  - - "·_·"
    - 2
  - - 橘子菌
    - 2
  - - Bluederoi
    - 2
  - - 元卞
    - 1
  - - Guinue
    - 2
  - - 小金睡不醒Zzz
    - 8
  - - Mr.Lee
    - 1
  - - Stone
    - 2
  - - morning breeze (能打版
    - 2
  - - 过禾
    - 2
  - - joe
    - 2
  - - 辣椒
    - 2
  - - 写完作业就回家
    - 6
  - - Luna
    - 2
  - - May
    - 2
  - - 伊比利亚小蛋糕🎂
    - 2
  - - 过禾
    - 2
  - - 於万斯年
    - 2
  - - 🎇
    - 1
  - - 🌈
    - 8
  - - 丶东方小妖
    - 2
  - - Spark (大肆哒嘟版)
    - 2
  - - 蕉蕉太狼
    - 2
  - - Milky
    - 2
  - - 予
    - 2
  - - 飞鱼
    - 6
  - - 西坡居士
    - 1
  - - 茫芊
    - 8
  - - 知意
    - 1
  - - (Π_Π)
    - 2
  - - 望仔小添才
    - 2
  - - 绵绵
    - 2
  - - 六便士
    - 6
  - - 潼潼
    - 2
  - - 该网名已被删除
    - 2
  - - Asterion
    - 2
  - - Lea
    - 8
  - - Vsilenstvi
    - 2
  - - 波波
    - 2
  - - Mayfly
    - 1.88
  - - 虎浪嘿🐅
    - 6
  - - 古木朽株
    - 6
  - - lyj
    - 2
  - - now or never
    - 2
  - - 叶瑄老婆
    - 2
  - - |-
      @￥]*t)
    - 6
  - - .22
    - 4
  - - L.
    - 2
  - - 软糖硬吃
    - 2
  - - Re_
    - 2
  - - 念安.
    - 2
  - - 山风
    - 18
  - - 昰言
    - 2
  - - Smile:)
    - 2
  - - A筱
    - 2
  - - 应如是
    - 2
  - - AB
    - 2
  - - Aysm
    - 2
  - - 小t小t
    - 8
  - - ski.di
    - 2
  - - 床
    - 6
  - - 霁月
    - 8
  - - 柒
    - 2
  - - Mq
    - 1
  - - _
    - 6
  - - 迪胖胖呀
    - 8
  - - 帆
    - 2
  - - 云深不知处
    - 2
  - - 曙
    - 2
  - - ✌
    - 2
  - - Flipped
    - 2
  - - 飞鸿踏雪泥
    - 18
  - - Bel-ami
    - 2
  - - "12345"
    - 2
  - - x
    - 8
  - - 🌖
    - 2
  - - Why
    - 8
  - - "@张恒瑞"
    - 2
  - - Kujo Jotaro
    - 2
  - - ENE
    - 6
  - - 十月流光
    - 2
  - - 等到放晴那天了🍂
    - 1
  - - 下眉头上心头
    - 8
  - - 遇语
    - 6
  - - SUNSHINE
    - 2
  - - AAA碧尔盖子在此
    - 6
  - - 白马即墨
    - 2
  - - attached
    - 2
  - - 北方有佳人
    - 8
  - - 在在
    - 2
  - - 乌拉哆啦
    - 6
  - - 寂川
    - 18
  - - QQmian
    - 2
  - - Herision哈里
    - 8
  - - 瘦咸鱼
    - 8
  - - 歌起楚江
    - 6
  - - 孤独星球
    - 2
  - - 我的id呢?
    - 2
  - - 何佳莽
    - 2
  - - 起向未来
    - 1
  - - 正义该溜子大战科二
    - 2
  - - -7³
    - 2
  - - 今盐
    - 2
  - - 豆芽
    - 2
  - - 神落十歌
    - 2
  - - 沙琪玛
    - 2
  - - 言说鳗饺
    - 6
  - - 中华小当当
    - 1
  - - 硬糖
    - 6
  - - Xavier
    - 2
  - - Devoted FUTURE
    - 2
  - - |-
      onandon4: 14
    - 8
  - - LKFWD
    - 2
  - - 肆门
    - 2
  - - 清风故里人
    - 2
  - - 魂
    - 6
  - - 陆王炸
    - 2
  - - N.A
    - 2
  - - 秋冬
    - 6
  - - 烂柯人
    - 2
  - - 振金士豆挠子
    - 2
  - - MADAO
    - 2
  - - 曙色
    - 1.66
  - - 无木息
    - 18
  - - 小新青年
    - 2
  - - 杨枝甘露醇
    - 2
  - - 江酒酒
    - 2
  - - Intrepid
    - 2
  - - Rechlieu
    - 6
  - - 睡觉莓
    - 2
  - - 🚀刘小远
    - 2
  - - wolf_8
    - 6
  - - 不上层楼
    - 18
  - - 唐小桐
    - 8
  - - 洛希极限
    - 2
  - - 🤯🤯🤯
    - 2
  - - 大聪明有大智慧
    - 8
  - - 落月屋梁
    - 1
  - - 叮咚CN
    - 2
  - - 来年
    - 2
  - - 碱性劣等生
    - 1
  - - Quarter
    - 2
  - - Alatreon
    - 6.66
  - - 纪清弦
    - 2
  - - 王落灰
    - 2
  - - 欧比旺克诺比
    - 1.14
  - - ferry
    - 1
  - - 南宫十七
    - 2
  - - Octavia🌠(拾荒版)
    - 2
  - - 要好好睡觉
    - 2
  - - 百事可乐Ovo
    - 2
  - - SALTWATER
    - 2
  - - Felix Felicis
    - 18
  - - 海绵宝宝(放假版)
    - 6
  - - Trigger
    - 2
  - - 海绵宝宝(放假版)
    - 6
  - - 鑫😊
    - 8
  - - (一些我实在打不出来的符号)
    - 8
  - - zzzzlz
    - 2
  - - ASIK
    - 2
  - - 波
    - 8
    - 8
  - - 孙py
    - 6
  - - 董畅达
    - 2
  - - LDN
    - 2
  - - zxp
    - 2
  - - 稼轩
    - 2.1
  - - dallas
    - 38
  - - " "
    - 2
  - - 超级无敌大大垃圾人
    - 2
  - - 太易宇
    - 2
  - - Lumos
    - 2
  - - Hannah's Lemonade
    - 18
  - - 南沫
    - 12.68
  - - 猫秋
    - 6.66
  - - 佚名
    - 1
  - - 柠月如风
    - 6.66
  - - 佚名
    - 1.88
  - - 平安忌災
    - 16.66
  - - 星
    - 18.88
  - - 青青草原
    - 18.88
  - - ·L·
    - 1.88
  - - 蒋利
    - 6.66
  - - 美丽心情
    - 6.66
  - - 胡炎
    - 6.66
  - - 永恒
    - 6.66
  - - 心雨
    - 6.66
  - - 佚名
    - 6.66
  - - 晓星尘
    - 1.88
  - - 佚名
    - 1.88
  - - 希昱科技
    - 6.66
  - - 晓琪
    - 6.66
  - - 菊
    - 12.68
  - - 晴方好
    - 6.66
  - - 飞鸿踏雪
    - 1.88
  - - 敏锐
    - 18.88
  - - 好运连连
    - 12.68
  - - 哈哥🐟
    - 88.88
  - - 小蓉蓉
    - 12.68
  - - 佚名
    - 6.66
  - - yi
    - 18.88
  - - 丁~美丽多一点
    - 26.88
  - - 水木清华
    - 1
  - - 栀子
    - 17.77
  - - 明了
    - 6.66
  - - 晓
    - 18.88
  - - 双双
    - 88.88
  - - 文文
    - 18.88
  - - 愿做春风暖人心
    - 166.66
  - - 揣一袋快乐吖~
    - 12.68
  - - 静夜望月
    - 6.66
  - - 佚名
    - 6.66
  - - 岁月静好
    - 35.68
  - - 天天快乐
    - 35.68
  - - Ufo
    - 50
  - - 木子
    - 6.66
  - - 佚名
    - 18.88
  - - HapPy娜
    - 18.88
  - - 海洋
    - 88.88
  - - 李伟
    - 12.68
  - - 六月
    - 35.68
  - - 修元
    - 6.66
  - - 赵艳英
    - 6.66
  - - 🌻🌻
    - 8
  - - 初夏
    - 66
  - - candies.
    - 8
  - - 发条人
    - 8
  - - 硬饭粒子
    - 2
  - - elk
    - 6
  - - 春和景
    - 2
  - - 云染
    - 18
  - - 水墨丹青
    - 18
  - - 秋宇大闲人
    - 2
  - - 鲤鱼
    - 2
  - - 旅游卡
    - 6
  - - Why
    - 6
  - - AAA碧儿盖子在此
    - 6
  - - 欣欣向荣
    - 6
  - - 认识你自己
    - 2
  - - 对方正在输入中...
    - 6
  - - ¿
    - 18
  - - (-_-)
    - 2
  - - ZFQ
    - 6
  - - 世行
    - 2
  - - 是小明呀
    - 8
  - - 长白山的雪
    - 1
  - - 猫猫虫
    - 2
  - - 各自安好
    - 2
  - - 快乐
    - 2
  - - 床帘拉开出太阳了
    - 2
  - - 倔强的小牛
    - 8
  - - LY
    - 2
  - - —— (燕)
    - 6
  - - 是小明呀
    - 18
  - - 杨枝甘露醇
    - 2
  - - C₈H₁₁NO₂
    - 6
  - - zxp
    - 2
  - - 来年
    - 2
  - - 贝贝贝贝贝塔
    - 6
  - - YOLO
    - 8
  - - structure d dedicated
    - -1
  - - 飞鱼
    - 6
  - - 纪清弦
    - 6
  - - Miraitowa
    - 6
  - - bhk
    - 8
  - - _
    - 2
  - - 一切都好
    - 8
  - - 大紫葡萄超好吃哒
    - 2
  - - 孙py
    - 20
  - - ⭐
    - 6
  - - 抬头微笑&壹生
    - 8
  - - 二营长菜菜子
    - 6
  - - -7³
    - 6
  - - 威莲
    - 2
  - - 小摸仙
    - 1
  - - F.
    - 6
  - - 萌萌哒的小企鹅
    - 2
  - - 寂川
    - 2
  - - wlw
    - 6
  - - 开心就好巴😀
    - 1
  - - 好名
    - 2
  - - 帆
    - 2
  - - 一定要早睡
    - 2
  - - 裴即玉 (未来可期版)
    - 2
  - - 贺俊浩
    - 8
  - - Tu
    - 2
  - - Smile:)
    - 2
  - - 野有蔓草 (精神错乱版)
    - 8
  - - Limen.
    - 2
  - - 伯瑛
    - 6
  - - 【无法识别的7个方框】
    - 1
  - - Future。
    - 2
  - - 落月屋梁
    - 1
  - - Toward
    - 1
  - - Shine
    - 6
  - - oxygen
    - 2
  - - FOGGY
    - 6
  - - Y🌇
    - 2
  - - 李子明
    - 2
  - - 赜琦
    - 6
  - - 是小明呀
    - 66
  - - 闲菜
    - 2
  - - 云卿-Lumen
    - 2
  - - dallas
    - 8
  - - 白告
    - 1
  - - Yu
    - 2
  - - 李颐涵
    - 8.66
  - - 葳蕤
    - 14
  - - 林海海的海cn
    - 18
  - - 谈谈笑笑，跑跑跳跳
    - 6
  - - Upstream 🌊
    - 2
  - - |-
      11.53
    - 2
  - - 云深之处~
    - 6.66
  - - |-
      *c
    - 2
  - - 南风如意
    - 6.66
  - - 李颐涵
    - 6.66
  - - 幸福安康
    - 88.88
  - - 7一
    - 6.66
  - - 信科某家长 gwj
    - 88.88
  - - 迷糊
    - 18.88
  - - sunshine
    - 66.66
  - - 森林
    - 12.68
  - - 娜
    - 35.68
  - - 梦特娇婷
    - 6.66
  - - 逸闻晟事
    - 6.66
  - - 不忘初心
    - 18.88
  - - 蒋利
    - 18.88
