title: 长春龙嘉机场服务
icon: contact
desc: 相关资料来自长春市龙嘉国际机场官网
author: Mr.Hope
time: 2023-09-23T10:52:59.665Z
shareable: true
cite: http://www.ccairport.cn/List/introduce
content:
  - tag: p
    text:
      - 特殊旅客服务是长春龙嘉国际机场针对航站楼内老、弱、病、残、孕、幼等特殊群体旅客(以下简称为特殊群体旅客)设立的服务项目。
      - 为方便特殊群体旅客出行，解决特殊群体旅客遇到的困难，长春机场立足于旅客角度深入考虑，本着“服务无极限、真诚零距离”的服务理念，免费为特殊群体旅客提供以下服务项目。

  - tag: text
    type: info
    header: 轮椅使用服务
    text: 为行动不便且未申请航空公司特服的旅客提供免费的轮椅使用

  - tag: text
    type: info
    header: 无人陪伴服务
    text: 为 70 岁以上(含)单独出行的老人和 5-12 周岁的无成人陪伴儿童提供进、出港流程全程陪送服务

  - tag: text
    type: info
    header: 特殊旅客优先登机服务
    text: 在登机口，对老弱病残孕及抱小孩的特殊群体旅客，工作人员会引导其优先登机

  - tag: text
    type: info
    header: 空铁联运服务
    text: 长春机场“金达莱”服务组与长春铁路客运站“轮椅姐”朱立红班组组成空铁联运服务伙伴，宗旨是为重点、特殊群体旅客的出行提供便捷的换乘服务。

  - tag: title
    text: 预约服务办理流程

  - tag: ol
    text:
      - 如旅客已购买机票，则需在机场办理乘机手续时提出相关申请，因各航空公司根据机型等情况有特殊服务数量限制，旅客应尽量提前向航空公司提出申请。
      - 如旅客需机场提供特殊旅客服务，则应详细记录旅客姓名、联系方式、乘机时间、乘坐航班号，并将预留信息告知地服候机服务台，相关部门及时联系旅客为旅客提供服务。
      - 地面服务保障部门接到旅客特殊服务申请，在符合运输条件的前提下，要做出合理安排以提供相应服务。如特殊原因不能提供服务，需向旅客做出解释，并做出妥善安排。
      - 长春机场南航分公司按南航总公司相关流程提供特殊旅客服务，即旅客购票时提出相关申请，或办理乘机手续时由其根据运力情况合理安排。
