title: 长春龙嘉机场动车组
icon: railway
desc: 相关资料来自长春市龙嘉国际机场官网
author: Mr.Hope
time: 2023-09-23T10:52:59.667Z
shareable: true
cite: http://www.ccairport.cn/Traffic/train
content:
  - tag: title
    text: 长春-吉林城际高速铁路简介

  - tag: p
    text:
      - 长珲城际铁路龙嘉高铁站位于长春龙嘉国际机场 T1 航站楼正南方向，与机场南侧公路并行，站房形式为地下车站。长珲城铁成为国内第一条实现铁路和空港间零换乘的城际铁路。从城铁下来的乘客可以通过地下通道直接步行抵达航站楼。龙嘉站可乘高铁直达长春火车站、长春西站以及吉林站。
      - 龙嘉高铁站与长春龙嘉国际机场 T2 航站楼有地下连廊，需要从 1 号通廊向北步行至与 3 号通廊交界处后，一直向东前进即可到达。

  - tag: ul
    header: 长春站 ↔ 龙嘉站
    text:
      - 长春站至龙嘉站每天 24 车次，历时 14 分钟
      - 龙嘉站至长春站每天 22 车次，历时 14 分钟

  - tag: ul
    header: 长春西站 ↔ 龙嘉站
    text:
      - 长春西站至龙嘉站往返每天 3 车次，历时 27 分钟
      - 龙嘉站至长春西站每日 1 班次，历时 27 分钟

  - tag: ul
    type: info
    header: 长春-吉林城际高速铁路列票价
    text:
      - |-
        长春站 ↔ 龙嘉站: 一等座 15 元，二等座 8.5 元
      - |-
        长春西站 ↔ 龙嘉站: 一等座 25 元，二等座 14.5 元

  - tag: title
    text: 列车时刻

  - tag: text
    type: warning
    text:
      - 以下时刻仅供参考，请以 12306 网站最终安排为准

  - tag: img
    src: $img/traffic/train-changchun-airport.png
    desc: 长春-龙嘉-吉林

  - tag: img
    src: $img/traffic/train-airport-changchun.png
    desc: 吉林-龙嘉-长春
